---
abstract: 'Provide interoperable MD5-based crypt() functions'
author:
  - 'Luis E. Munoz <luismunoz@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  Test::More: '1.001002'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.62, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Crypt-PasswdMD5
no_index:
  directory:
    - t
    - inc
requires:
  Digest::MD5: '2.53'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/ronsavage/Crypt-PasswdMD5/issues
  license: http://opensource.org/licenses/Perl
  repository: https://github.com/ronsavage/Crypt-PasswdMD5.git
version: '1.42'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
